### ISSUE TITLE
NameError: name 'plugin_process' is not defined 

### ISSUE THREAD

**Issue by gsienkoPL** [PANOimagen/LiDARForestryHeight#1]
Hello. I have this error when trying to use this plugin.

An error has occurred while executing Python code: 

NameError: name 'plugin_process' is not defined 
Traceback (most recent call last):
  File "D:/Users/gsienko/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LiDARForestryHeight-master\LiDARForestryHeight_dialog.py", line 158, in preparingProcess
    self.settingProcessParams(full_filename, outPath)
  File "D:/Users/gsienko/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LiDARForestryHeight-master\LiDARForestryHeight_dialog.py", line 198, in settingProcessParams
    self.process = plugin_process.Process(full_filename,
NameError: name 'plugin_process' is not defined

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.8.2-Zanzibar Zanzibar, 4470baa1a3 

Python Path:
D:/Users/gsienko/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools
C:/OSGEO4~1/apps/qgis/./python
D:/Users/gsienko/AppData/Roaming/QGIS/QGIS3\profiles\default/python
D:/Users/gsienko/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\lib\site-packages
D:/Users/gsienko/AppData/Roaming/QGIS/QGIS3\profiles\default/python
D:\eclipse\plugins\org.python.pydev.core_7.0.3.201811082356\pysrc
D:\Users\gsienko\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
D:\Users\gsienko\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
D:\Users\gsienko\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms
D:/Users/gsienko/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\joinmultiplelines
D:\Users\gsienko\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms

**Comment by RobertoPanoi** [comment]
Hi, Thanks for using our plugin. 
Because the LasPy library is not installed by default in QGIS, the plugin had code that verified that installation but was not done in the correct way.
We have updated the code in the new version (0.2), I would appreciate it if you try again. I hope you find it useful

**Comment by gsienkoPL** [comment]
Hello. In 0.2 i have another issue:

```Couldn't load plugin 'LiDARForestryHeight-master' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'scipy' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "D:/Users/gsienko/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LiDARForestryHeight-master\__init__.py", line 38, in classFactory
    from .LiDARForestryHeight import LiDARForestryHeight
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "D:/Users/gsienko/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LiDARForestryHeight-master\LiDARForestryHeight.py", line 34, in 
    from .LiDARForestryHeight_dialog import LiDARForestryHeightDialog
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "D:/Users/gsienko/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LiDARForestryHeight-master\LiDARForestryHeight_dialog.py", line 43, in 
    from . import plugin_process
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "D:/Users/gsienko/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LiDARForestryHeight-master\plugin_process.py", line 32, in 
    from . import raster_funs as raster_fns
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "D:/Users/gsienko/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LiDARForestryHeight-master\raster_funs.py", line 28, in 
    import scipy
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'scipy'


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.8.2-Zanzibar Zanzibar, 4470baa1a3 

Python Path:
D:/Users/gsienko/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pdaltools
D:/Users/gsienko/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools
C:/OSGEO4~1/apps/qgis/./python
D:/Users/gsienko/AppData/Roaming/QGIS/QGIS3\profiles\default/python
D:/Users/gsienko/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\lib\site-packages
D:/Users/gsienko/AppData/Roaming/QGIS/QGIS3\profiles\default/python
D:\eclipse\plugins\org.python.pydev.core_7.0.3.201811082356\pysrc
D:\Users\gsienko\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
D:\Users\gsienko\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
D:\Users\gsienko\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms
D:/Users/gsienko/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\joinmultiplelines
D:\Users\gsienko\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
```

I need to install scipy manually is osgeo4w shell. Now it's work fine.

**Comment by RobertoPanoi** [comment]
Ok. In version 0.1, due to how the search for the LasPy library was managed, other possible errors were hidden, in case there was another Python library not installed. In version 0.2 thats solved.

Thanks!
