### ISSUE TITLE
Plugin crash on load of  QGIS version 3.24.3-Tisler

### ISSUE THREAD

**Issue by dpoursanidis** [PANOimagen/LiDARForestryHeight#3]
Couldn't load plugin 'LiDARForestryHeight-master' due to an error when calling its classFactory() method 

ImportError: cannot import name 'Header' from 'laspy.header' (C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\laspy\header.py) 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LiDARForestryHeight-master\__init__.py", line 38, in classFactory
    from .LiDARForestryHeight import LiDARForestryHeight
  File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LiDARForestryHeight-master\LiDARForestryHeight.py", line 34, in 
    from .LiDARForestryHeight_dialog import LiDARForestryHeightDialog
  File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LiDARForestryHeight-master\LiDARForestryHeight_dialog.py", line 43, in 
    from . import plugin_process
  File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LiDARForestryHeight-master\plugin_process.py", line 31, in 
    from . import laspy_funs as laspy_fns
  File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LiDARForestryHeight-master\laspy_funs.py", line 39, in 
    from laspy.header import Header
ImportError: cannot import name 'Header' from 'laspy.header' (C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\laspy\header.py)

Any idea? Need to install other packages?

**Comment by Empanag** [comment]
> Couldn't load plugin 'LiDARForestryHeight-master' due to an error when calling its classFactory() method
> 
> ImportError: cannot import name 'Header' from 'laspy.header' (C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\laspy\header.py) Traceback (most recent call last): File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin plugins[packageName] = package.classFactory(iface) File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LiDARForestryHeight-master__init__.py", line 38, in classFactory from .LiDARForestryHeight import LiDARForestryHeight File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin__init__.py", line 38, in **wrapping_ee_import** _module_ = **builtin_import**(name, *args, **kwargs) File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import mod = _builtin_import(name, globals, locals, fromlist, level) File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LiDARForestryHeight-master\LiDARForestryHeight.py", line 34, in from .LiDARForestryHeight_dialog import LiDARForestryHeightDialog File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin__init__.py", line 38, in **wrapping_ee_import** _module_ = **builtin_import**(name, *args, **kwargs) File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import mod = _builtin_import(name, globals, locals, fromlist, level) File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LiDARForestryHeight-master\LiDARForestryHeight_dialog.py", line 43, in from . import plugin_process File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin__init__.py", line 38, in **wrapping_ee_import** _module_ = **builtin_import**(name, *args, **kwargs) File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import mod = _builtin_import(name, globals, locals, fromlist, level) File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LiDARForestryHeight-master\plugin_process.py", line 31, in from . import laspy_funs as laspy_fns File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin__init__.py", line 38, in **wrapping_ee_import** _module_ = **builtin_import**(name, *args, **kwargs) File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import mod = _builtin_import(name, globals, locals, fromlist, level) File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LiDARForestryHeight-master\laspy_funs.py", line 39, in from laspy.header import Header ImportError: cannot import name 'Header' from 'laspy.header' (C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\laspy\header.py)
> 
> Any idea? Need to install other packages?

Same issue here

**Comment by Sickculture** [comment]
Same issue. Running newest QGIS 3.42.0 Münster
